# If the DB is populated, but you want to wipe it out to start with a fresh seeding, 
# run the below command first:
#                        "rake db:migrate:reset"  
# This will drop all, create the DB (with all tables), then remigrate all.




seconds = ScoreContext.create!(description: "boring 'ol seconds", perSecondVariable: 1, outputStart: "", outputEnd: " seconds passed.  Yeah, not real interesting, is it?  PICK A DIFFERENT CONTEXT!", unit: "seconds", image: "https://66.media.tumblr.com/a3360cf64800079574ebda2d58a02178/tumblr_inline_ol4mqmyQGd1qekxju_640.gifv")
sound = ScoreContext.create!(description: "The speed of sound", perSecondVariable: 0.21313027, outputStart: "an object moving at the speed of sound traveled ", outputEnd: " miles.", unit: "miles", image: "https://i.pinimg.com/originals/f6/57/c8/f657c875461381c86bc86204d8c7b2e9.gif")
light = ScoreContext.create!(description: "The speed of light", perSecondVariable: 186000, outputStart: "an object moving at the speed of light traveled ", outputEnd: " miles.", unit: "miles", image: "https://i.imgur.com/RuJYgPu.gif")
population = ScoreContext.create!(description: "Global population increase", perSecondVariable: 2.6, outputStart: "the global population rose by ", outputEnd: " people.", unit: "people", image: "http://theworld-today.weebly.com/uploads/4/4/5/9/44595823/2082223.gif")
earth =ScoreContext.create!(description: "Distance the Earth has traveled around the Sun", perSecondVariable: 18.50553929, outputStart: "the Earth traveled ", outputEnd: " miles around the sun.", unit: "miles", image: "https://i.imgur.com/YXn5xQN.gif")
bezos = ScoreContext.create!(description: "Jeff Bezos's fortune increase", perSecondVariable: 3182.87037, outputStart: "Jeff Bezos's fortune increased by $", outputEnd: ".", unit: "dollars", image: "https://assets.entrepreneur.com/content/3x2/2000/20190607142532-jeff-bezos.jpeg")
tweets = ScoreContext.create!(description: "tweets sent", perSecondVariable: 6000, outputStart: "", outputEnd: " tweets were sent worldwide.", unit: "tweets", image: "https://cdn.ilovefreesoftware.com/wp-content/uploads/2017/06/twitter-gif-downloader.gif")
moon = ScoreContext.create!(description: "Distance the Moon has traveled around the Earth", perSecondVariable: 0.635, outputStart: "the Moon traveled ", outputEnd: " miles around the Earth.", unit: "miles", image: "https://res.cloudinary.com/jerrick/image/upload/w_720/otzzmunvucte85o5b9ie.gif")
iss = ScoreContext.create!(description: "Distance traveled by the International Space Station", perSecondVariable: 4.76, outputStart: "the International Space Station traveled ", outputEnd: " miles.", unit: "miles", image: "https://robbreportedit.files.wordpress.com/2019/06/iss056e201174.jpg")

soundFact1 = Fact.create!(score_context_id: sound.id, details: "When traveling through water, sound moves around four times faster than when it travels through air.")
soundFact2 = Fact.create!(score_context_id: sound.id, details: "The sound of thunder is produced by rapidly heated air surrounding lightning which expands faster than the speed of sound.")
soundFact3 = Fact.create!(score_context_id: sound.id, details: "The most loudest natural sound on Earth is caused by an erupting volcano.")
soundFact4 = Fact.create!(score_context_id: sound.id, details: "The majority of cows which listen to music end up producing more milk than those that do not.")
lightFact1 = Fact.create!(score_context_id: light.id, details: "While in space astronauts sometimes see random flashes of light caused by cosmic rays hitting the optic nerve. We don’t see it on earth because the magnetosphere protects us from the rays.")
lightFact2 = Fact.create!(score_context_id: light.id, details: "Peacock feathers are actually brown, but have microscopic structures that interfere with light that make the bright iridescence.")
lightFact3 = Fact.create!(score_context_id: light.id, details: "Due to time dilation one could travel thousands of light years in a single human lifespan without exceeding the speed of light.")
lightFact4 = Fact.create!(score_context_id: light.id, details: "Unlike sound waves or water waves, light does not need any matter or material to carry its energy along. Thus, light can travel through a vacuum.")
populationFact1 = Fact.create!(score_context_id: population.id, details: "The world’s population is growing by 1.10 percent per year, or approximately an additional 83 million people annually. ")
populationFact2 = Fact.create!(score_context_id: population.id, details: "50.4 percent of the world’s population is male and 49.6 percent is female.")
populationFact3 = Fact.create!(score_context_id: population.id, details: "For half a century, China has been the most populated country in the world. This will change, as India is expected to overtake China by 2022. Additionally, the United States will lose its third-place spot to Nigeria.")
populationFact4 = Fact.create!(score_context_id: population.id, details: "Monaco currently has the most dense population in the world. The independent city-state of Monaco may be the second smallest sovereign state in the world, but it’s population is far from small. Despite only covering .78 square miles, it has a population of 38,897. This evens out to about 26,105 people per square kilometer.")
earthFact1 = Fact.create!(score_context_id: earth.id, details: "Every year, the Earth travels 92.96 million miles around the sun, at a rate of 66,620 miles per hour!  WOW!")
earthFact2 = Fact.create!(score_context_id: earth.id, details: "Earth is the only planet not named for a mythological god or goddess. The other seven planets in the solar system were named after Roman gods or goddesses. The word “Earth” comes from the Old English word “ertha” meaning ground or land.")
earthFact3 = Fact.create!(score_context_id: earth.id, details: "The rotation of the Earth is gradually slowing down. The deceleration of the Earth’s rotation is very slow, approximately 17 milliseconds per hundred years. Eventually this will lengthen our days but it will take around 140 million years before our day will have increased from 24 to 25 hours.")
earthFact4 = Fact.create!(score_context_id: earth.id, details: "70% of the Earth’s surface is covered by water – the remainder consists of continents and islands which together have many lakes and other sources of water.")
bezosFact1 = Fact.create!(score_context_id: bezos.id, details: "According to the Bloomberg Billionaires Index, Bezos' net worth on 1/1/2019 was $99 billion. On 5/1/2019, it was $132 billion, meaning it rose $33 billion.")
bezosFact2 = Fact.create!(score_context_id: bezos.id, details: "Jeff Bezos was adopted at a young age by his stepfather, Miguel 'Mike' Bezos, an engineer at Exxon.")
bezosFact3 = Fact.create!(score_context_id: bezos.id, details: "The first item ever to be sold on Jeff’s Amazon.com is a science textbook titled “Fluid Concepts & Creative Analogies: Computer Models of the Fundamental Mechanisms of Thought”.")
bezosFact4 = Fact.create!(score_context_id: bezos.id, details: "When Bezos spends $1.7 million, that's like the average American spending $1.")
tweetsFact1 = Fact.create!(score_context_id: tweets.id, details: "It took 3 years, 2 months and 1 day to get to the billionth tweet. Today it only takes one week for users to send a billion tweets.")
tweetsFact2 = Fact.create!(score_context_id: tweets.id, details: "10 tweets per second mention Starbucks.")
tweetsFact3 = Fact.create!(score_context_id: tweets.id, details: "32% of all Internet users are using Twitter.")
tweetsFact4 = Fact.create!(score_context_id: tweets.id, details: "Lady Gaga, Justin Bieber and Katy Perry have more Twitter followers than the entire populations of Germany, Turkey, South Africa, Canada, Argentina and Egypt.")
moonFact1 = Fact.create!(score_context_id: moon.id, details: "The Moon orbits the earth at a relative speed of 2286 miles per hour!")
moonFact2 = Fact.create!(score_context_id: moon.id, details: "The rise of fall of tides on Earth is caused by the Moon. Two bulges exist due to the gravitational pull the Moon exerts. One is on the side facing the Moon and the other on the side facing away from it. These bulges move around the oceans as the Earth rotates which causes the high and low tides found across the globe.")
moonFact3 = Fact.create!(score_context_id: moon.id, details: "The Moon has quakes. The gravitational pull of Earth causes small moonquakes several kilometres beneath the surface – causing ruptures and cracks. It is believed that, like Earth, the Moon has a molten core.")
moonFact4 = Fact.create!(score_context_id: moon.id, details: "There is no atmosphere on the Moon. There is no protection for the surface from cosmic rays, meteorites, asteroids, comets, or solar winds. This is why the Moon has such huge temperature variations and it is covered with impact craters. The lack of atmosphere also means no sound can be heard on the Moon and the sky is always black.")
issFact1 = Fact.create!(score_context_id: iss.id, details: "The ISS travels at a staggering 17,150 miles per hour!")
issFact2 = Fact.create!(score_context_id: iss.id, details: "The ISS is the single most expensive object ever built. The cost of the ISS has been estimated at over $120 billion.")
issFact3 = Fact.create!(score_context_id: iss.id, details: "There are only two bathrooms on the entire station. The urine of both the crewmembers and laboratory animals is filtered back into the station’s drinking water supply, so at least the astronauts will never get thirsty. ")
issFact4 = Fact.create!(score_context_id: iss.id, details: "Because the human body tends to lose muscle and bone mass in zero gravity environments, all astronauts aboard the ISS must work out at least two hours a day to maintain normal Earth-based bodily health.  ")

tom = User.create!(name: "Tom", login_id: "TomM", password: "12345")
andy = User.create!(name: "Andy", login_id: "AndyC", password: "12345")
joe = User.create(name: "Joe", login_id: "Joe_E", password: "12345")
sarah = User.create(name: "Sarah", login_id: "Sarah87", password: "12345")
melanie = User.create(name: "Melanie", login_id: "Mel_E_Knee", password: "12345")



game1 = Game.create!(name: "Letters Typer", componentName: "LettersGame")
game2 = Game.create!(name: "Numbers Typer", componentName: "NumbersGame")
ScoreHistory.create!(game_id: game1.id, user_id: tom.id, score: 15.345)
ScoreHistory.create!(game_id: game2.id, user_id: tom.id, score: 15.345)
ScoreHistory.create!(game_id: game1.id, user_id: tom.id, score: 21.345)
ScoreHistory.create!(game_id: game2.id, user_id: tom.id, score: 21.345)
ScoreHistory.create!(game_id: game1.id, user_id: andy.id, score: 12.345)
ScoreHistory.create!(game_id: game2.id, user_id: andy.id, score: 14.745)
ScoreHistory.create!(game_id: game1.id, user_id: andy.id, score: 23.335)
ScoreHistory.create!(game_id: game2.id, user_id: andy.id, score: 25.945)
ScoreHistory.create!(game_id: game1.id, user_id: joe.id, score: 15.345)
ScoreHistory.create!(game_id: game1.id, user_id: joe.id, score: 12.985)
ScoreHistory.create!(game_id: game1.id, user_id: joe.id, score: 14.355)
ScoreHistory.create!(game_id: game1.id, user_id: melanie.id, score: 13.355)
ScoreHistory.create!(game_id: game1.id, user_id: melanie.id, score: 18.355)
ScoreHistory.create!(game_id: game1.id, user_id: melanie.id, score: 17.355)
ScoreHistory.create!(game_id: game1.id, user_id: sarah.id, score: 13.655)
ScoreHistory.create!(game_id: game1.id, user_id: sarah.id, score: 18.375)
ScoreHistory.create!(game_id: game1.id, user_id: sarah.id, score: 17.359)
ScoreHistory.create!(game_id: game2.id, user_id: joe.id, score: 15.345)
ScoreHistory.create!(game_id: game2.id, user_id: joe.id, score: 12.985)
ScoreHistory.create!(game_id: game2.id, user_id: joe.id, score: 14.355)
ScoreHistory.create!(game_id: game2.id, user_id: melanie.id, score: 13.355)
ScoreHistory.create!(game_id: game2.id, user_id: melanie.id, score: 18.355)
ScoreHistory.create!(game_id: game2.id, user_id: melanie.id, score: 17.355)
ScoreHistory.create!(game_id: game2.id, user_id: sarah.id, score: 13.655)
ScoreHistory.create!(game_id: game2.id, user_id: sarah.id, score: 18.375)
ScoreHistory.create!(game_id: game2.id, user_id: sarah.id, score: 17.359)


